moveo:
  Joint_state_controller:
    type: Joint_state_controller/JointStateController
    publish_rate: 50

  group_controller:
    type: "robot_controllers/FollowJointTrajectoryController"
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
